import { CareerProps } from "../types/careers";

export const CAREERS: CareerProps[] = [
  {
    position: "Stagiaire en Intelligence Artificielle",
    company: "Port Autonome de Douala (PAD)",
    logo: "/images/careers/pad.png",
    location: "Douala, Cameroun 🇨🇲",
    location_type: "Présentiel",
    type: "Stage académique",
    start_date: "2025-02",
    end_date: "2025-06",
    industry: "Transport maritime et logistique",
    link: "https://www.pad.cm/",
    responsibilities: [
      "Conception et développement d'un agent IA de codification des marchandises avec interface Chatbot",
      "Implémentation de la technologie RAG pour l'assistance dans le processus de codification",
      "Développement d'une application web moderne avec système de monitoring et logging embarqué",
      "Classification tarifaire des marchandises adaptée aux exigences du PAD",
    ],
    isShow: true,
  },
  {
    position: "Stagiaire en Informatique",
    company: "Port Autonome de Douala (PAD)",
    logo: "/images/careers/pad.png",
    location: "Douala, Cameroun 🇨🇲",
    location_type: "Présentiel",
    type: "Stage académique",
    start_date: "2024-06",
    end_date: "2024-08",
    industry: "Transport maritime et logistique",
    link: "https://www.pad.cm/",
    responsibilities: [
      "Développement d'une application mobile de fiche de pilotage",
      "Travail dans le département des Systèmes d'Information",
      "Analyse des besoins utilisateurs et conception de solutions adaptées",
    ],
    isShow: true,
  },
  {
    position: "Enseignant de Mathématiques, Physique et Informatique",
    company: "Intelligentsia Corporation",
    logo: "/images/careers/intelligentsia.png",
    location: "Yaoundé, Cameroun 🇨🇲",
    location_type: "Présentiel",
    type: "Temps partiel",
    start_date: "2021-06",
    end_date: "2024-08",
    industry: "Éducation",
    link: "#",
    responsibilities: [
      "Enseignement aux étudiants en classe préparatoire polytechnique",
      "Préparation des cours et exercices en mathématiques, physique et informatique",
      "Accompagnement pédagogique et suivi des progrès des étudiants",
      "Transmission des connaissances et développement de l'esprit critique",
    ],
    isShow: true,
  },
];
